import type { AppProps } from 'next/app';
import Head from 'next/head';

import '../styles/globals.css';

export default function App({ Component, pageProps, router }: AppProps) {
  return (
    <>
      <Head>
        <title>Next.js App</title>
        <meta name='description' content='Generated by create next app' />
        <meta property='og:url' content={`${process.env.NEXT_PUBLIC_DOMAIN}${router.asPath}`} />
        <meta property='og:locale' content='ru_RU' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&display=swap'
          rel='stylesheet'
        />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
