name: Publish Docker2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/dariavorom/top-app-nextjs:latest
          docker run ghcr.io/dariavorom/top-app-nextjs:latest
          docker push ghcr.io/dariavorom/top-app-nextjs:latest
